services:

  db:
    image: mysql:latest
    ports:
        - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypasswd

    networks:
        localnet:
            aliases:
                - mysql-default
    volumes:
        - ./config:/etc/mysql/conf.d
        - ./datadir:/var/lib/mysql

networks:
    localnet:
